host:
  # web api host
  # you can use API and Web interface through this host
  # webapi: docker.dev.example.net
  webapi: localhost

listen:
  # listen address
  # default is only listen from localhost
  foreign_address: 127.0.0.1

  # listen port and reverse proxy port
  http:
    # listen 8080 and transport to container's 5000 port
    - listen: 8080
      target: 5000

storage:
  htmldir: ./html

parameters:
  - name: branch
    env: GIT_BRANCH
    rule: ""
    required: true
  # add your custom parameters here!
  # name is parameter name (passed by HTTP parameter)
  # env is environment variable for docker container
  # rule is constraint of value using regexp.
  # required means required or optional parameter (boolean value)

ecs:
  region: ap-northeast-1
  cluster: mirage
  launch_type: FARGATE
  network_configuration:
    awsvpc_configuration:
      subnets:
        - '{{ env "SUBNET_A" "subnet-aaaaaa" }}'
        - '{{ env "SUBNET_B" "subnet-bbbbbb" }}'
      security_groups:
        - '{{ env "SECURITY_GROUP_1" "sg-111111" }}'
      assign_public_ip: ENABLED
  default_task_definition: '{{ env "DEFAULT_TASKDEF" "arn:aws:ecs:ap-northeast-1:123456789012:task-definition/myapp" }}'
